### ISSUE TITLE
onmouseover method instead classname ? Use other attr than classname ?

### ISSUE THREAD

**Issue by GunGunGun** [Fischer-L/previewbox#1]
Hi, is there a way that I can use onmouseover then show the preview box instead of I have to add class="previewbox-anchor", because sometime I still have to use class="" for other thing, and HTML doesn't allow double class attr

And is there a way to use other attribute than classname ?

Thank in adv!

**Comment by Fischer-L** [comment]
Not sure of what you mean by "HTML doesn't allow double class attr".
It is fine to apply multiple class selectors (use white space to separate them) to one HTML element.

**Comment by GunGunGun** [comment]
Thank you, I solved my problem.
