### ISSUE TITLE
Is it possible to click to preview instead of mouse hover?

### ISSUE THREAD

**Issue by lentm88** [Fischer-L/previewbox#2]
Hi, I was very impressed on your script.
But, is there an option to let this script click to preview instead of mouse hover?

**Comment by Fischer-L** [comment]
Hi,

First thanks for feedback.

About the "click to preview", it is possible to do.

However, there would be one ambiguous case, that is, when user explicitly clicks a link, should we prompt the preview box or bring them to that page.

By default user's experience, most users should expect click one link then open the page of this link.
What's more, if clicking is to preview, what action should be done to go to link's page ?

The greatest benefit of this preview plugin resides in that when user is reading one article, user can take a look at the content of other links inside article quickly & conveniently.

User doesn't have to open another page, which quite interrupts the current reading experience.
If user was more interested in external link and wanted to dive into that more, it is better to directly go to that page to read.

Thanks

**Comment by fpsvogel** [comment]
I was going to ask this same question because I was wondering how it would work on a touch screen, but it already works on my Android phone at least: the preview pops up with the first click/press, and the link is followed with a second one. Thanks for this script!

**Comment by Fischer-L** [comment]
An interesting case: phone/tablet.

My original target scenario is desktop browser. Phone & tablet is not checked.

However, it may be more useful for phone & tablet since switching between pages by finger is kind of bothering.

I will go checkout phone & tablet and see if any improvement could be done in this kind of scenario.

**Comment by Fischer-L** [comment]
Hi

Add the mobile/tablet support on both iOS and Android.

The switching between the PC and the mobile/tablet mode is automatic.

Please try.
