### ISSUE TITLE
Preview <a inside <img tag ?

### ISSUE THREAD

**Issue by anatasiajp** [Fischer-L/previewbox#3]
Hi Fis, is there a way to preview this kind of code ? I tried to register both a and img tag but nothong happen

Test HTML:
< a class=" previewbox-anchor" href="http://google.com">< img class=" previewbox-anchor" src="http://www.google.com/images/nav_logo195.png" border="0" width="80" height="80"></a>

Then I run this code:
        // Set up the demo
        for (var i = 0, as = document.getElementsByTagName("a"); i < as.length; i++) {
            previewbox.regisAnchor(as[i]);
        }
                for (var i = 0, as = document.getElementsByTagName("img"); i < as.length; i++) {
            previewbox.regisAnchor(as[i]);
        }
        previewbox.setSandbox("");

Thank

**Comment by Fischer-L** [comment]
Hi

Only <a> is surpported.

But why need to preview img?

User can see img unless u don't want user sees and hide img

**Comment by Fischer-L** [comment]
Sorry, didn't get your question right in the 1st place.

This works:

```
<a class="previewbox-anchor" href="xxxxx">
    <img src="xxxx" />
</a>
```

However, your example code should display an blank, empty preview box.

This is because of  X-Frame-Options (https://developer.mozilla.org/en-US/docs/HTTP/X-Frame-Options)

Google doesn't allow itself to be rendered inside iframe.

**Comment by anatasiajp** [comment]
I fixed the code, problem is your code cannot detect something like e.target.parentNode.href, that is the complexity of javascript, there is e.target.href and e.target.parentNode.href, if we want to detect as much <a as possible, we must also add e.target.parentNode.href conditition too, here is my patch:

Line: if (_isHref(e.target.href)) {

```
                if (_isHref(e.target.href)) {
                    _showBox(e.target.href, e.clientX, e.clientY);
                }
                                    else if (_isHref(e.target.parentNode.href)) {
                    _showBox(e.target.parentNode.href, e.clientX, e.clientY);
                }
```

And perfect:with all kind of <a

**Comment by Fischer-L** [comment]
Hi,

Could you please explain more detail about the problem you see ?

I just try again the following code:

```
    <a class="previewbox-anchor" href="http://www.wikipedia.org/">
        <img src="url_to_img_of_wikipedia" />
    </a>
```

The preview box for Wikipedia shows as expected.

That would be good if you could provide bug duplication SOP so I can test exactly what happens.

Thanks

**Comment by anatasiajp** [comment]
Thanks you for replying, I hope I can but I use Privoxy to test your code, at this time i'm very busy so I will reply this topic when I have time.
